version: "3.9"

services:
  backend:
    image: nautic-server:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nautic-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=/data/database.sqlite
      - DOCKER_SOCKET_PATH=/var/run/docker.sock
    volumes:
      - backend_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nautic-net

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: nautic-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:4000
    networks:
      - nautic-net

networks:
  nautic-net:
    driver: bridge
volumes:
  backend_data: