version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: nautic-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DOCKER_SOCKET_PATH=/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nautic-net

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: nautic-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:4000
    networks:
      - nautic-net
      
networks:
  nautic-net:
    driver: bridge
